/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(plsync_cc.h)                                               */
/* BINDTOOL_HEADER_FILE_HASH(0a8ef05229dca8050b4fe45a146e00b1)                     */
/***********************************************************************************/

#include <pybind11/chrono.h>
#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2rx/plframer_cc.h>
// pydoc.h is automatically generated in the build directory
#include <plframer_cc_pydoc.h>

void bind_plframer_cc(py::module& m)
{

    using plframer_cc = gr::dvbs2rx::plframer_cc;


    py::class_<plframer_cc, gr::block, gr::basic_block, std::shared_ptr<plframer_cc>>(
        m, "plframer_cc", D(plframer_cc))

        .def(py::init(&plframer_cc::make),
             py::arg("gold_code"),
             py::arg("freq_est_period"),
             py::arg("sps"),
             py::arg("debug_level"),
             py::arg("pls_code"),
             D(plframer_cc, make))
        .def("get_freq_offset",
             &plframer_cc::get_freq_offset,
             D(plframer_cc, get_freq_offset))

        .def("get_coarse_freq_corr_state",
             &plframer_cc::get_coarse_freq_corr_state,
             D(plframer_cc, get_coarse_freq_corr_state))
        .def("get_locked", &plframer_cc::get_locked, D(plframer_cc, get_locked))

        .def("get_sof_count", &plframer_cc::get_sof_count, D(plframer_cc, get_sof_count))

        .def("get_frame_count",
             &plframer_cc::get_frame_count,
             D(plframer_cc, get_frame_count))

        .def("get_rejected_count",
             &plframer_cc::get_rejected_count,
             D(plframer_cc, get_rejected_count))

        .def("get_dummy_count",
             &plframer_cc::get_dummy_count,
             D(plframer_cc, get_dummy_count))

        .def("get_lock_time", &plframer_cc::get_lock_time, D(plframer_cc, get_lock_time));
}
